


services:
  db_dev:
    image: postgres:latest
    container_name: reacon-db-dev
    networks:
      reacon-net-dev:
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      retries: 10
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=reacon_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env.development

  redis_dev:
    image: redis:8.0.1-alpine
    container_name: reacon-redis-cache-dev
    networks:
      reacon-net-dev:
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
    restart: always
    depends_on:
      db_dev:
        condition: service_healthy
    volumes:
      - redis-data-dev:/data
    ports:
      - "6379:6379"
    env_file:
      - .env.development


  api_dev:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    container_name: reacon-api-dev
    networks:
      - reacon-net-dev
    depends_on:
      db_dev:
        condition: service_healthy
      redis_dev:
        condition: service_healthy
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    command: sh ./entrypoint.dev.sh

  client_dev:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
      args:
      - VITE_BASE_URL= http://0.0.0.0:8000/api/
      - VITE_WS_ORIGIN= ws://0.0.0.0:8000
      - VITE_APP_NAME= Reacon
      - VITE_CLIENT_URL= http://0.0.0.0:5173/
    container_name: reacon-client-dev
    networks:
      - reacon-net-dev
    depends_on:
      api_dev:
        condition: service_started
    volumes:
      - ./client:/usr/src/app
      - node_modules_client-dev:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}
      VITE_WS_ORIGIN: ${VITE_WS_ORIGIN}
      VITE_APP_NAME: ${VITE_APP_NAME}
      VITE_CLIENT_URL: ${VITE_CLIENT_URL}
    env_file:
      - .env.development
    command: ["sh", "entrypoint.sh"]

networks:
  reacon-net-dev:
    driver: bridge

volumes:
  redis-data-dev: {}
  db-data-dev: {}
  node_modules_client-dev: {}


# secrets:
#   db-password:
#     file: db/password.txt
